// DMM API レスポンス模倣ダミーデータ
// API ID 取得前の UI 開発・シード用

import type { Article, Actress } from './types'

export const MOCK_ACTRESSES: Omit<Actress, 'id'>[] = [
  {
    external_id: 'mock-actress-001',
    name: '桜木りな',
    ruby: 'さくらぎりな',
    image_url: 'https://picsum.photos/seed/actress-rina/200/200',
    metadata: { debut_year: 2022, popularity: 95 },
    is_active: true,
  },
  {
    external_id: 'mock-actress-002',
    name: '水野ひかり',
    ruby: 'みずのひかり',
    image_url: 'https://picsum.photos/seed/actress-hikari/200/200',
    metadata: { debut_year: 2021, popularity: 88 },
    is_active: true,
  },
  {
    external_id: 'mock-actress-003',
    name: '花岡みく',
    ruby: 'はなおかみく',
    image_url: 'https://picsum.photos/seed/actress-miku/200/200',
    metadata: { debut_year: 2023, popularity: 82 },
    is_active: true,
  },
  {
    external_id: 'mock-actress-004',
    name: '倉田えみ',
    ruby: 'くらたえみ',
    image_url: 'https://picsum.photos/seed/actress-emi/200/200',
    metadata: { debut_year: 2020, popularity: 91 },
    is_active: true,
  },
  {
    external_id: 'mock-actress-005',
    name: '木村なな',
    ruby: 'きむらなな',
    image_url: 'https://picsum.photos/seed/actress-nana/200/200',
    metadata: { debut_year: 2022, popularity: 78 },
    is_active: true,
  },
  {
    external_id: 'mock-actress-006',
    name: '田中あかね',
    ruby: 'たなかあかね',
    image_url: 'https://picsum.photos/seed/actress-akane/200/200',
    metadata: { debut_year: 2021, popularity: 85 },
    is_active: true,
  },
  {
    external_id: 'mock-actress-007',
    name: '藤本ゆり',
    ruby: 'ふじもとゆり',
    image_url: 'https://picsum.photos/seed/actress-yuri/200/200',
    metadata: { debut_year: 2023, popularity: 72 },
    is_active: true,
  },
  {
    external_id: 'mock-actress-008',
    name: '宮本さや',
    ruby: 'みやもとさや',
    image_url: 'https://picsum.photos/seed/actress-saya/200/200',
    metadata: { debut_year: 2020, popularity: 89 },
    is_active: true,
  },
  {
    external_id: 'mock-actress-009',
    name: '橋本まお',
    ruby: 'はしもとまお',
    image_url: 'https://picsum.photos/seed/actress-mao/200/200',
    metadata: { debut_year: 2022, popularity: 76 },
    is_active: true,
  },
  {
    external_id: 'mock-actress-010',
    name: '上田れいこ',
    ruby: 'うえだれいこ',
    image_url: 'https://picsum.photos/seed/actress-reiko/200/200',
    metadata: { debut_year: 2019, popularity: 93 },
    is_active: true,
  },
]

export const MOCK_ARTICLES: Omit<Article, 'id' | 'fetched_at'>[] = [
  {
    external_id: 'mock-article-001',
    title: '桜木りな 初めての独り占め 4時間スペシャル',
    slug: 'sakuragi-rina-4h-special-mock-ar01',
    source: 'dmm-mock',
    category: '単体作品',
    tags: ['桜木りな', '単体作品', 'HQ', '4K'],
    summary: '人気急上昇中の桜木りながついに単体作品で登場。全4時間の大ボリュームで彼女の魅力を余すことなく収録した傑作。',
    content: '桜木りなが初の単体作品でファンの期待に応えます。4時間に渡る作品の中で彼女の様々な表情をお楽しみください。\n\n今作では従来の枠を超えた挑戦的なシーンも多数収録。撮影は3日間にわたって行われました。',
    image_url: 'https://picsum.photos/seed/mock-article-001/600/340',
    published_at: '2026-04-20T10:00:00Z',
    metadata: { actress_name: '桜木りな', actress_id: 'mock-actress-001', series: null, label: 'Premium Works' },
    is_active: true,
  },
  {
    external_id: 'mock-article-002',
    title: '桜木りな バレンタイン限定 甘い一日',
    slug: 'sakuragi-rina-valentine-mock-ar02',
    source: 'dmm-mock',
    category: 'ドラマ',
    tags: ['桜木りな', 'ドラマ', 'バレンタイン', 'ロマンス'],
    summary: 'バレンタインデーに贈る特別企画。桜木りなが演じるロマンチックなストーリーに心奪われる作品。',
    content: 'チョコレートの甘い香りとともに展開するラブストーリー。\n\n二人の距離が縮まる瞬間を丁寧に描いた作品です。',
    image_url: 'https://picsum.photos/seed/mock-article-002/600/340',
    published_at: '2026-02-14T09:00:00Z',
    metadata: { actress_name: '桜木りな', actress_id: 'mock-actress-001', series: 'Season Special', label: 'Romance Studio' },
    is_active: true,
  },
  {
    external_id: 'mock-article-003',
    title: '水野ひかり ACT.2 最強の輝き',
    slug: 'mizuno-hikari-act2-mock-ar03',
    source: 'dmm-mock',
    category: '単体作品',
    tags: ['水野ひかり', '単体作品', 'HQ', '独占配信'],
    summary: '昨年大ヒットしたACT.1の続編がついに登場。より大人びた魅力で帰ってきた水野ひかりの最新作。',
    content: 'ACT.1から約1年、水野ひかりはさらなる成長を遂げ、圧倒的な存在感でスクリーンを支配します。\n\nシリーズ最高の完成度との声も上がる注目作。',
    image_url: 'https://picsum.photos/seed/mock-article-003/600/340',
    published_at: '2026-04-18T10:00:00Z',
    metadata: { actress_name: '水野ひかり', actress_id: 'mock-actress-002', series: 'ACT Series', label: 'Hikari Films' },
    is_active: true,
  },
  {
    external_id: 'mock-article-004',
    title: '水野ひかり バラエティ全開！素顔のひかりちゃん',
    slug: 'mizuno-hikari-variety-mock-ar04',
    source: 'dmm-mock',
    category: 'バラエティ',
    tags: ['水野ひかり', 'バラエティ', '素顔', 'トーク'],
    summary: 'カメラの前で素直な素顔を見せてくれるバラエティ企画。ゲームや料理、トークなど盛りだくさんの内容。',
    content: 'バラエティならではの自然体な水野ひかりが楽しめる一作。\n\n視聴者から大好評だった前作に続く企画第2弾。',
    image_url: 'https://picsum.photos/seed/mock-article-004/600/340',
    published_at: '2026-03-05T11:00:00Z',
    metadata: { actress_name: '水野ひかり', actress_id: 'mock-actress-002', series: null, label: 'Variety Max' },
    is_active: true,
  },
  {
    external_id: 'mock-article-005',
    title: '花岡みく アイドル完全版 Dream Gift',
    slug: 'hanaoka-miku-dream-gift-mock-ar05',
    source: 'dmm-mock',
    category: 'アイドル',
    tags: ['花岡みく', 'アイドル', 'ライブ', '完全版'],
    summary: '花岡みくのアイドル活動を完全収録。ライブパフォーマンスからバックステージまで、ファン必見の一作。',
    content: 'デビューから現在までの軌跡を振り返る完全版。\n\n未公開映像も多数収録した豪華仕様となっています。',
    image_url: 'https://picsum.photos/seed/mock-article-005/600/340',
    published_at: '2026-04-15T10:00:00Z',
    metadata: { actress_name: '花岡みく', actress_id: 'mock-actress-003', series: 'Idol Complete', label: 'Dream Stage' },
    is_active: true,
  },
  {
    external_id: 'mock-article-006',
    title: '花岡みく グラビア写真集 SAKURA',
    slug: 'hanaoka-miku-gravure-sakura-mock-ar06',
    source: 'dmm-mock',
    category: 'グラビア',
    tags: ['花岡みく', 'グラビア', '写真集', '春'],
    summary: '春をテーマにした花岡みくのグラビア写真集。桜をバックに撮影された美しいカットが満載。',
    content: '春の陽光の中で輝く花岡みくの魅力を余すことなく収録した写真集。\n\n撮影は京都・奈良を中心に行われました。',
    image_url: 'https://picsum.photos/seed/mock-article-006/600/340',
    published_at: '2026-03-20T09:00:00Z',
    metadata: { actress_name: '花岡みく', actress_id: 'mock-actress-003', series: 'Gravure Collection', label: 'Photo Works' },
    is_active: true,
  },
  {
    external_id: 'mock-article-007',
    title: '倉田えみ プレミアム 4K 最高峰の美',
    slug: 'kurata-emi-premium-4k-mock-ar07',
    source: 'dmm-mock',
    category: '単体作品',
    tags: ['倉田えみ', '単体作品', '4K', 'プレミアム'],
    summary: '最高品質の映像で届ける倉田えみのプレミアム作品。4K映像で彼女の魅力が更に際立つ傑作。',
    content: '4K撮影技術を駆使して制作された最高品質の作品。\n\n国内最大級の制作スタジオで3日間にわたって撮影されました。',
    image_url: 'https://picsum.photos/seed/mock-article-007/600/340',
    published_at: '2026-04-10T10:00:00Z',
    metadata: { actress_name: '倉田えみ', actress_id: 'mock-actress-004', series: 'Premium 4K', label: 'Ultra HD Films' },
    is_active: true,
  },
  {
    external_id: 'mock-article-008',
    title: '倉田えみ × 特別企画 コスプレ大全集',
    slug: 'kurata-emi-cosplay-mock-ar08',
    source: 'dmm-mock',
    category: '企画',
    tags: ['倉田えみ', '企画', 'コスプレ', '特集'],
    summary: '倉田えみが様々なコスプレに挑戦した特別企画。アニメキャラから制服まで20種類以上のコスプレを披露。',
    content: 'ファンリクエストを元に選ばれた20以上のコスプレで倉田えみが変身。\n\n衣装へのこだわりも見どころの一つです。',
    image_url: 'https://picsum.photos/seed/mock-article-008/600/340',
    published_at: '2026-02-28T11:00:00Z',
    metadata: { actress_name: '倉田えみ', actress_id: 'mock-actress-004', series: 'Special Project', label: 'Cosplay Studio' },
    is_active: true,
  },
  {
    external_id: 'mock-article-009',
    title: '木村なな DEBUT 2nd SEASON',
    slug: 'kimura-nana-debut-2nd-mock-ar09',
    source: 'dmm-mock',
    category: '単体作品',
    tags: ['木村なな', '単体作品', '独占配信', 'デビュー記念'],
    summary: 'デビューから1年、木村ななが更なる成長を見せる第二章。ファンの声援に応えた渾身の一作。',
    content: 'デビュー1周年を記念して制作された木村なな渾身の2nd SEASON。\n\n前作から大きな進化を見せる力作です。',
    image_url: 'https://picsum.photos/seed/mock-article-009/600/340',
    published_at: '2026-04-08T10:00:00Z',
    metadata: { actress_name: '木村なな', actress_id: 'mock-actress-005', series: 'Debut Season', label: 'New Wave' },
    is_active: true,
  },
  {
    external_id: 'mock-article-010',
    title: '木村なな ロマンス 愛のカタチ',
    slug: 'kimura-nana-romance-ai-mock-ar10',
    source: 'dmm-mock',
    category: 'ドラマ',
    tags: ['木村なな', 'ドラマ', 'ロマンス', '純愛'],
    summary: '純愛をテーマにした木村ななの渾身のドラマ作品。繊細な感情表現が光る感動的な一作。',
    content: '愛の様々なカタチを描いたロマンス大作。\n\n脚本・演出ともに高い評価を受けた話題作です。',
    image_url: 'https://picsum.photos/seed/mock-article-010/600/340',
    published_at: '2026-03-15T09:00:00Z',
    metadata: { actress_name: '木村なな', actress_id: 'mock-actress-005', series: null, label: 'Romance Studio' },
    is_active: true,
  },
  {
    external_id: 'mock-article-011',
    title: '田中あかね バラエティ爆笑SP 全3時間',
    slug: 'tanaka-akane-variety-sp-mock-ar11',
    source: 'dmm-mock',
    category: 'バラエティ',
    tags: ['田中あかね', 'バラエティ', 'スペシャル', 'トーク'],
    summary: '抜群のトーク力で笑いを届ける田中あかねのバラエティスペシャル。企画満載の3時間。',
    content: 'あかね節炸裂！笑いあり感動ありの充実の3時間バラエティ。\n\n人気ゲストを多数招いた豪華な顔ぶれにも注目です。',
    image_url: 'https://picsum.photos/seed/mock-article-011/600/340',
    published_at: '2026-04-05T11:00:00Z',
    metadata: { actress_name: '田中あかね', actress_id: 'mock-actress-006', series: 'Variety SP', label: 'Comedy Works' },
    is_active: true,
  },
  {
    external_id: 'mock-article-012',
    title: '田中あかね アイドル写真集 あかいろ',
    slug: 'tanaka-akane-idol-photo-mock-ar12',
    source: 'dmm-mock',
    category: 'アイドル',
    tags: ['田中あかね', 'アイドル', '写真集', '春夏'],
    summary: '赤をテーマにした田中あかねの初写真集「あかいろ」。春夏の鮮やかなシーンが収録されたファン必携の一冊。',
    content: '田中あかねの名前に込められた「赤」をテーマに展開する写真集。\n\n全100ページの大ボリュームで届けます。',
    image_url: 'https://picsum.photos/seed/mock-article-012/600/340',
    published_at: '2026-03-01T09:00:00Z',
    metadata: { actress_name: '田中あかね', actress_id: 'mock-actress-006', series: 'Photo Book', label: 'Idol Press' },
    is_active: true,
  },
  {
    external_id: 'mock-article-013',
    title: '藤本ゆり グラビア EX 究極の曲線美',
    slug: 'fujimoto-yuri-gravure-ex-mock-ar13',
    source: 'dmm-mock',
    category: 'グラビア',
    tags: ['藤本ゆり', 'グラビア', '水着', '独占配信'],
    summary: 'グラビア界注目の藤本ゆりが究極のボディラインを披露。プロカメラマンが捉えた最高傑作。',
    content: 'スタジオ撮影から海外ロケまで多彩なシーンで構成されたグラビア大作。\n\n沖縄・バリ島でのロケ映像も収録しています。',
    image_url: 'https://picsum.photos/seed/mock-article-013/600/340',
    published_at: '2026-04-01T10:00:00Z',
    metadata: { actress_name: '藤本ゆり', actress_id: 'mock-actress-007', series: 'Gravure EX', label: 'Body Arts' },
    is_active: true,
  },
  {
    external_id: 'mock-article-014',
    title: '藤本ゆり 企画 制服コレクション100着',
    slug: 'fujimoto-yuri-uniform-mock-ar14',
    source: 'dmm-mock',
    category: '企画',
    tags: ['藤本ゆり', '企画', '制服', 'コレクション'],
    summary: '100種類の制服に挑戦する前代未聞の企画作品。学生服からメイドまで多彩な制服で魅了する。',
    content: '1日1着、100日間にわたる撮影で完成した壮大な制服コレクション。\n\n衣装の一部はファンからの提供品です。',
    image_url: 'https://picsum.photos/seed/mock-article-014/600/340',
    published_at: '2026-02-20T11:00:00Z',
    metadata: { actress_name: '藤本ゆり', actress_id: 'mock-actress-007', series: null, label: 'Project Films' },
    is_active: true,
  },
  {
    external_id: 'mock-article-015',
    title: '宮本さや 完全版 LEGEND',
    slug: 'miyamoto-saya-legend-mock-ar15',
    source: 'dmm-mock',
    category: '単体作品',
    tags: ['宮本さや', '単体作品', 'BEST', '完全版'],
    summary: 'キャリア6年を誇る宮本さやの集大成。全過去作からのベストシーン集に加え、新撮下ろし映像も収録。',
    content: '宮本さやの輝かしいキャリアを一作に凝縮したLEGEND作品。\n\n撮影終了後に本人がコメントを収録した特典映像も付属します。',
    image_url: 'https://picsum.photos/seed/mock-article-015/600/340',
    published_at: '2026-03-28T10:00:00Z',
    metadata: { actress_name: '宮本さや', actress_id: 'mock-actress-008', series: 'Legend Series', label: 'Premium BEST' },
    is_active: true,
  },
  {
    external_id: 'mock-article-016',
    title: '宮本さや ロマンス 冬の温もり',
    slug: 'miyamoto-saya-romance-winter-mock-ar16',
    source: 'dmm-mock',
    category: 'ドラマ',
    tags: ['宮本さや', 'ドラマ', '冬', 'ロマンス'],
    summary: '冬の日本を舞台にした切ないラブストーリー。宮本さやの演技力が光る感動作。',
    content: '雪降る街で偶然出会った二人の純愛を描いた作品。\n\n劇中使用のサウンドトラックも好評発売中です。',
    image_url: 'https://picsum.photos/seed/mock-article-016/600/340',
    published_at: '2026-01-30T09:00:00Z',
    metadata: { actress_name: '宮本さや', actress_id: 'mock-actress-008', series: null, label: 'Drama Studio' },
    is_active: true,
  },
  {
    external_id: 'mock-article-017',
    title: '橋本まお 真剣勝負 FIGHT BACK',
    slug: 'hashimoto-mao-fight-back-mock-ar17',
    source: 'dmm-mock',
    category: 'アクション',
    tags: ['橋本まお', 'アクション', '格闘', 'HQ'],
    summary: '女優としての一面を超え、アクション女優としての橋本まおが覚醒。迫力満点のアクションシーンが連発。',
    content: '武術の訓練を重ねた橋本まおが繰り広げる本格アクション作品。\n\nスタント不使用のリアルファイトシーンは必見です。',
    image_url: 'https://picsum.photos/seed/mock-article-017/600/340',
    published_at: '2026-03-22T10:00:00Z',
    metadata: { actress_name: '橋本まお', actress_id: 'mock-actress-009', series: 'Fight Series', label: 'Action Studio' },
    is_active: true,
  },
  {
    external_id: 'mock-article-018',
    title: '橋本まお アイドル BLOSSOM',
    slug: 'hashimoto-mao-idol-blossom-mock-ar18',
    source: 'dmm-mock',
    category: 'アイドル',
    tags: ['橋本まお', 'アイドル', '春', 'ライブ'],
    summary: '春の到来を彩る橋本まおのアイドル作品「BLOSSOM」。満開の花々とともに歌い踊る輝かしい一作。',
    content: '春をテーマにしたライブパフォーマンスと撮影が一体となった作品。\n\n全曲書き下ろしのオリジナルソングを収録しています。',
    image_url: 'https://picsum.photos/seed/mock-article-018/600/340',
    published_at: '2026-02-10T09:00:00Z',
    metadata: { actress_name: '橋本まお', actress_id: 'mock-actress-009', series: 'Blossom', label: 'Idol Stage' },
    is_active: true,
  },
  {
    external_id: 'mock-article-019',
    title: '上田れいこ バラエティ クッキング with れいちゃん',
    slug: 'ueda-reiko-cooking-variety-mock-ar19',
    source: 'dmm-mock',
    category: 'バラエティ',
    tags: ['上田れいこ', 'バラエティ', 'クッキング', '料理'],
    summary: '料理上手で知られる上田れいこがプロの料理家と共演。本格料理から家庭料理まで多彩なレシピを披露。',
    content: '視聴者から寄せられたレシピを上田れいこが実際に作る人気企画。\n\n全30レシピを収録した豪華版です。',
    image_url: 'https://picsum.photos/seed/mock-article-019/600/340',
    published_at: '2026-03-10T11:00:00Z',
    metadata: { actress_name: '上田れいこ', actress_id: 'mock-actress-010', series: 'Cooking Show', label: 'Life Style' },
    is_active: true,
  },
  {
    external_id: 'mock-article-020',
    title: '上田れいこ グラビア10周年記念 DECADE',
    slug: 'ueda-reiko-decade-gravure-mock-ar20',
    source: 'dmm-mock',
    category: 'グラビア',
    tags: ['上田れいこ', 'グラビア', '10周年', 'BEST'],
    summary: 'グラビア活動10周年を迎えた上田れいこの記念作品「DECADE」。10年分の進化と美しさが凝縮された一作。',
    content: '10年のキャリアを振り返るとともに、現在の姿を最高の形で届ける記念作品。\n\nファンへのメッセージ動画も特典として収録しました。',
    image_url: 'https://picsum.photos/seed/mock-article-020/600/340',
    published_at: '2026-01-15T10:00:00Z',
    metadata: { actress_name: '上田れいこ', actress_id: 'mock-actress-010', series: 'Anniversary', label: 'Premium Gravure' },
    is_active: true,
  },
]
