export type SocialActress = {
  name: string
  screenName: string  // X username without @
  recommended?: boolean
}

export const SOCIAL_FEED_ACTRESSES: SocialActress[] = [
  // ── ⭐ おすすめ女優（21名） ──────────────────────────────────────────
  { name: 'MINAMO',         screenName: 'M_I_N_A_M_O_',      recommended: true },
  { name: '井上もも',       screenName: 'momoinoue99',         recommended: true },
  { name: '伊藤舞雪',       screenName: 'mayuki_ito_',         recommended: true },
  { name: '佐々木さき',     screenName: 'Sasaki_Saki',         recommended: true },
  { name: '八木奈々',       screenName: 'yaginana0903',        recommended: true },
  { name: '北岡果林',       screenName: 'karin_kitaoka_',      recommended: true },
  { name: '博多彩葉',       screenName: 'iroha_0108_',         recommended: true },
  { name: '小野六花',       screenName: 'onorikka',            recommended: true },
  { name: '川越にこ',       screenName: 'kawagoeniko',         recommended: true },
  { name: '彩月七緒',       screenName: 'nao_satsuki',         recommended: true },
  { name: '東條なつ',       screenName: '_tojo_natsu',         recommended: true },
  { name: '松本いちか',     screenName: 'MatuMoto_Ich1ka',     recommended: true },
  { name: '瀬戸環奈',       screenName: 'kanna_seto0510',      recommended: true },
  { name: '白石透羽',       screenName: 'towashira14',         recommended: true },
  { name: '石原希望',       screenName: 'Nozomi_Ishihara',     recommended: true },
  { name: '石川澪',         screenName: '_ishikawamio_',       recommended: true },
  { name: '福田ゆあ',       screenName: 'yua_fucuda',          recommended: true },
  { name: '花守夏歩',       screenName: 'hanamorikaho',        recommended: true },
  { name: '莉々はるか',     screenName: 'ririharuka_',         recommended: true },
  { name: '逢沢みゆ',       screenName: 'Aizawa_miyu03',       recommended: true },
  { name: '青空ひかり',     screenName: 'aozora_cmore',        recommended: true },
  // ── その他登録女優（121名） ──────────────────────────────────────────
  { name: 'miru',           screenName: 'miruteer_29'          },
  { name: 'RARA',           screenName: '_R_A_R_A2nd'          },
  { name: 'YUUKA',          screenName: 'newwife_yuuka'        },
  { name: 'YUUKA',          screenName: 'YUUKAsbu'             },
  { name: 'うんぱい',       screenName: 'unpai3'               },
  { name: 'さつき芽衣',     screenName: 'satsuki_meisabu'      },
  { name: 'ゆうき希',       screenName: 'NozomiYukiAct'       },
  { name: '一ノ瀬恋',       screenName: 'ichinose_ren_m'       },
  { name: '七ツ森りり',     screenName: 'riri_nntmr'           },
  { name: '七沢みあ',       screenName: 'mia_nanasawa'         },
  { name: '七瀬アリス',     screenName: 'Alice_Nanase_'        },
  { name: '三上悠亜',       screenName: 'yua_mikami'           },
  { name: '三咲まゆ',       screenName: 'mayu_misaki0801'      },
  { name: '三好佑香',       screenName: 'Miyoshi_style'        },
  { name: '三田真鈴',       screenName: 'mitamarin0628'        },
  { name: '五日市芽衣',     screenName: '5may_itsukaichi'      },
  { name: '佐野ゆま',       screenName: 'sanoyumasan_gao'      },
  { name: '佐野りか',       screenName: 'sano_rika_'           },
  { name: '倉木華',         screenName: 'hana_kuraki87'        },
  { name: '兒玉七海',       screenName: 'KodamaNanami'         },
  { name: '千咲ちな',       screenName: 'chinadayo'            },
  { name: '吉高寧々',       screenName: 'yoshitakanene'        },
  { name: '咲月ひな',       screenName: 'satsuki_hina'         },
  { name: '園梨音',         screenName: 'rinon_sono'           },
  { name: '塚本さや',       screenName: 'saya_sflirt'          },
  { name: '夏川ゆの',       screenName: 'yuno_natsukawa'       },
  { name: '天使もえ',       screenName: 'amatsuka_moe'         },
  { name: '天川そら',       screenName: 'iamSORA_AMAKAWA'      },
  { name: '天神羽衣',       screenName: 'amagami_cmore'        },
  { name: '天宮花南',       screenName: 'amamiya_kanan'        },
  { name: '奥田咲',         screenName: 'okusakinyan'          },
  { name: '女神ジュン',     screenName: 'Megami_Jun_'          },
  { name: '妃ひかり',       screenName: 'hikari__kisaki'       },
  { name: '姫咲はな',       screenName: 'hana_himesak212'      },
  { name: '安達夕莉',       screenName: 'yuuri_adachi'         },
  { name: '安齋らら',       screenName: 'rara_ansai'           },
  { name: '宮下玲奈',       screenName: 'rena_miyashita'       },
  { name: '宮島めい',       screenName: 'miyajima100'          },
  { name: '小倉由菜',       screenName: 'ogu_yuna'             },
  { name: '小宵こなん',     screenName: 'konankoyoiOA'         },
  { name: '小島みなみ',     screenName: 'kojima373'            },
  { name: '小日向みゆう（清原みゆう）', screenName: 'miyu_kohinata' },
  { name: '小日向める',     screenName: 'kohinata_mel'         },
  { name: '小笠原菜乃',     screenName: 'nano_ogasawara'       },
  { name: '小沢菜穂',       screenName: 'Ozawa__Naho'          },
  { name: '小栗操',         screenName: 'misa_Oguri'           },
  { name: '小野坂ゆいか',   screenName: 'yuika_onosaka'        },
  { name: '小野寺舞',       screenName: 'onoderamai_'          },
  { name: '山岸逢花',       screenName: 'ayakayamagishi_'      },
  { name: '幸村泉希',       screenName: 'ituki_yukimura'       },
  { name: '愛才りあ',       screenName: 'aise_ria'             },
  { name: '新井リマ',       screenName: 'Arai_rima'            },
  { name: '新川空',         screenName: 'nami_sora_star'       },
  { name: '明日葉みつは',   screenName: 'ashitaba_taba'        },
  { name: '明里つむぎ',     screenName: 'akari_tsumugi__'      },
  { name: '星仲ここみ',     screenName: 'coco3hoshinak'        },
  { name: '有村のぞみ',     screenName: 'nozomi_arimura'       },
  { name: '有栖舞衣',       screenName: 'arisumai'             },
  { name: '木村愛心',       screenName: 'ako_kimu'             },
  { name: '未歩なな',       screenName: 'miho_nanachan'        },
  { name: '末広純',         screenName: 'suehiro_jun'          },
  { name: '本庄鈴',         screenName: 'honjosuzu'            },
  { name: '本間あさ美',     screenName: 'asami__honma'         },
  { name: '東実果',         screenName: 'Azuma_Mika_'          },
  { name: '松本菜奈実',     screenName: '7mim_sub'             },
  { name: '枢木あおい',     screenName: 'Aoi_krrg'             },
  { name: '桜乃りの',       screenName: 'sakurano_rino'        },
  { name: '桜空もも',       screenName: 'sakumomo1203'         },
  { name: '森亜秋',         screenName: 'ao5zx_uxux0'          },
  { name: '森日向子',       screenName: 'morihinako_'          },
  { name: '橘いおり',       screenName: 'tachibana_iorin'      },
  { name: '永瀬みゆう',     screenName: 'Miyuu_sflirt'         },
  { name: '河北彩伽',       screenName: 'saika_kawakita'       },
  { name: '河合あすな',     screenName: 'kawai_asuna'          },
  { name: '青坂あおい',     screenName: 'aoi_aosaka'           },
  { name: '今田光',         screenName: 'imada_hikari'         },
  { name: '大浦真奈美',     screenName: 'manami_oura'          },
  { name: '矢埜愛茉',       screenName: 'yano_ema'             },
  { name: '桐谷すずね',     screenName: 'kiritanisuzune'       },
  { name: '和香なつき',     screenName: 'waka_natsuki_ys'      },
  { name: '栗山莉緒',       screenName: 'Kuriyama_Rio'         },
  { name: '水卜さくら',     screenName: 'archemiura'           },
  { name: '水彩あき',       screenName: 'aki_mizusa7777'       },
  { name: '古乃ほの',       screenName: 'furuno_hono'          },
  { name: '瀧本雫葉',       screenName: 'shizuhatakimoto'      },
  { name: '泉ももか',       screenName: 'momoca_izm'           },
  { name: '巴ひかり',       screenName: 'hikari1207t'          },
  { name: '和久井美兎',     screenName: 'wakui_mito_'          },
  { name: '市川まさみ',     screenName: 'ichikawa_masami'      },
  { name: '鈴村あいり',     screenName: 'airi_mgr'             },
  { name: '泉りおん',       screenName: '_izumirion'           },
  { name: '浅野こころ',     screenName: 'korokorococoroo'      },
  { name: '浜辺やよい',     screenName: 'yayoi_hamabe'         },
  { name: '涼森れむ',       screenName: 'remu_suzumori'        },
  { name: '深田えいみ',     screenName: 'fukada0318'           },
  { name: '渚あいり',       screenName: 'Nagisa_Airi'          },
  { name: '渡部ほの',       screenName: 'watanabe_h0n0'        },
  { name: '田野憂',         screenName: '_yu_8_8'              },
  { name: '由衣陽菜',       screenName: 'yuihinapiyo'          },
  { name: '白上咲花',       screenName: 'emika_shirakami'      },
  { name: '白岩冬萌',       screenName: 'tomo_shiraiwa'        },
  { name: '白石なみ',       screenName: 'naminamisira'         },
  { name: '白石純',         screenName: 'shiraishi_jun_'       },
  { name: '神喜ミア',       screenName: 'kokimia_2'            },
  { name: '神木彩（月雲よる）', screenName: 'Tsukumo_aya'     },
  { name: '篠原いよ',       screenName: 'iyo_shinohara'        },
  { name: '篠真有',         screenName: 'shino_mayuyu'         },
  { name: '純白彩永',       screenName: 'mashiro__sana'        },
  { name: '紗倉まな',       screenName: 'sakuramanaTeee'       },
  { name: '紫堂るい',       screenName: 'rui_shido'            },
  { name: '結月りあ',       screenName: 'yuzuki_ria'           },
  { name: '葵いぶき',       screenName: 'aoi__ibuki'           },
  { name: '藤井蘭々',       screenName: 'ranran_ru808'         },
  { name: '西元めいさ',     screenName: 'nishimotomeisa'       },
  { name: '西尾まりな',     screenName: 'nishio_marina8'       },
  { name: '金松季歩',       screenName: 'kiho_kanematsu'       },
  { name: '鈴の家りん',     screenName: 'rinrin_dayou'         },
  { name: '鈴木希',         screenName: 'noso0824'             },
  { name: '長浜みつり',     screenName: 'mitsuri_n0601'        },
  { name: '雛形みくる',     screenName: 'mikuru__hi'           },
  { name: '雨宮ひびき',     screenName: 'Amamiya_816'          },
  { name: '香水じゅん',     screenName: 'jun_kasui'            },
  { name: '鳳みゆ',         screenName: 'ootori_miyu'          },
  { name: '黒島玲衣',       screenName: 'kuroshima_rei'        },
]
